name: Deploy to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure id
      run: echo ${{ secrets.AZURE_CLIENT_ID }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Bicep
      run: |
        sudo az bicep install


    - name: Deploy Bicep
      run: |
        az deployment group create --resource-group rg-practice3 --template-file task1.bicep
        az deployment group create --resource-group rg-practice3 --template-file azure-resource.bicep

    - name: Delete resource
      run: |
        az resource delete --resource-group rg-practice3 --name example146340639 --resource-type Microsoft.Storage/storageAccounts

